### ISSUE TITLE
Is it possible to connect with query parameters?

### ISSUE THREAD

**Issue by losedges** [ricardopereira/SocketIO-Kit#21]
In my current project socket clients are connected with "query {Authorization: etc}
in web console : Object {transport: "polling", Authorization: "Bearer .....
I tried to add a method "query" the same way like to "namespace" added 
 "withOptions: SocketIOOptions().namespace ", but this option does not work for me

where I am wrong?

**Comment by ricardopereira** [comment]
Unfortunately SocketIO-Kit doesn't support query or custom headers but in a future release. It's not planned but it's a good feature.

**Comment by losedges** [comment]
Thanks for the quick response!

**Comment by ricardopereira** [comment]
:+1:
